# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-29 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u', models.CharField(max_length=50)),
                ('v', models.CharField(max_length=50)),
                ('bus', models.CharField(max_length=50, null=True)),
                ('cost', models.FloatField()),
                ('distance', models.FloatField()),
                ('time', models.FloatField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='graph',
            unique_together=set([('u', 'v', 'bus', 'cost', 'time', 'distance')]),
        ),
    ]
